server:
  port: 9001
  shutdown: graceful

logging:
  config: classpath:log4j2-spring.xml

spring:
  application:
    name: weibo-subscribe-public
  datasource:
    name: hikariDataSource
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weibo_subscribe?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 12
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: select 'x'
      max-lifetime: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml

---
weibo:
  subscribe:
    telegramChatId: -1001885177644
    telegramBotToken: 5458704928:AAHBqZFKpu4T8EEGAJFPDT4FNfGqwxoOlGs
    cyclePeriod: 3
    proxy: http://127.0.0.1:7890 # international network proxy configuration,local run or debug